# Generated by Django 6.0.7 on 2026-07-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_category',
            field=models.CharField(default='Class A', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Van', 'Van'), ('Sedan', 'Sedan'), ('Other', 'Other')], default='Truck', max_length=20),
        ),
    ]
