# Generated by Django 6.0.7 on 2026-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driver_contact_number_driver_license_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], default='North', max_length=20),
        ),
    ]
